//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/Scripts/Player/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""726b7934-942e-4c2c-8740-7e64eab3e062"",
            ""actions"": [
                {
                    ""name"": ""PauseMenu"",
                    ""type"": ""Button"",
                    ""id"": ""885048c3-b71e-4ca1-a6ca-08648a4a9b07"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""9db66482-3fc3-462b-a80e-a934bb45d4d8"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""UseTool"",
                    ""type"": ""Button"",
                    ""id"": ""f5344e3b-8b29-40c0-8324-7a6e141f02ed"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlantCrop1"",
                    ""type"": ""Button"",
                    ""id"": ""2067b151-1542-4568-baa4-62e77a925e8e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlantCrop2"",
                    ""type"": ""Button"",
                    ""id"": ""982372ef-201f-4e73-9dbe-c44bb69fbfbb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlantCrop3"",
                    ""type"": ""Button"",
                    ""id"": ""39506356-b63c-4d40-ae76-90ac9b6f7abb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlantCrop4"",
                    ""type"": ""Button"",
                    ""id"": ""414988c7-b9d6-44dc-95b0-c8905b0a10a4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlantCrop5"",
                    ""type"": ""Button"",
                    ""id"": ""27f8022f-d7da-485f-9d35-ae0ea75c8adb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD [Keyboard]"",
                    ""id"": ""e99e3afe-9f7c-48c0-b770-a78dcbbabdca"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""ba19aee9-2e0a-49c2-bb19-0086d2be8c22"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Player1"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""e80f36c2-1b9c-4ea2-8686-6d4cfe62fc7d"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Player1"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a304bf1e-5ec5-4d55-9c18-cf6c8cb9e18e"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Player1"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""8b196f4c-563c-4c98-9559-aac549110b18"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Player1"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""IJKL [Keyboard]"",
                    ""id"": ""4033672c-71de-48e2-8cab-eea267721a60"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""30a0aaa5-1f83-431e-b0ef-7cd9b8609ef1"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Player2"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""6f0b4974-e840-4b83-b1cb-5a47bb63708d"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Player2"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""edcc52b6-f79e-4ecf-a5c3-cec41d0e9979"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Player2"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""f906c033-b6df-4da9-a988-9cc967afc5c6"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Player2"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""0aecab2c-c099-4f59-8cdc-3fcaeb4e88bf"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Player1"",
                    ""action"": ""PlantCrop1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bbda5e23-9377-45a1-b03c-839f934d9ed0"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Player2"",
                    ""action"": ""PlantCrop1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""30b4ce1b-0525-4c8d-b86c-427110120a3f"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Player1"",
                    ""action"": ""PlantCrop2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""baad7c41-a2d6-4127-9c75-a29795fa0886"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Player2"",
                    ""action"": ""PlantCrop2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d9fdce21-4101-43d6-9019-4c8a30b32f67"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Player1"",
                    ""action"": ""PlantCrop3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1bfcc909-0a7d-4285-86c6-211e703b2ab2"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Player2"",
                    ""action"": ""PlantCrop3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""14c90380-bb58-47be-b52c-5327acad735e"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Player1"",
                    ""action"": ""PlantCrop4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cc13ecdf-bfdb-479f-a345-d24ba6f8af5a"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Player2"",
                    ""action"": ""PlantCrop4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d52fee7c-53e1-43ae-8350-f3cdbd99f7b3"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Player1"",
                    ""action"": ""PlantCrop5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""61086e8f-e3f4-40fc-bbb3-f3727718c672"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Player2"",
                    ""action"": ""PlantCrop5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e093a0c6-3520-47bc-9654-c2da7b0c86ce"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Player1"",
                    ""action"": ""UseTool"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8addf344-6e5b-416a-8071-2868fe297cb0"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Player2"",
                    ""action"": ""UseTool"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a77e21dd-4f80-4c88-847e-b7c99e6baaf5"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Player1;Player2"",
                    ""action"": ""PauseMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Player1"",
            ""bindingGroup"": ""Player1"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Player2"",
            ""bindingGroup"": ""Player2"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_PauseMenu = m_Gameplay.FindAction("PauseMenu", throwIfNotFound: true);
        m_Gameplay_Movement = m_Gameplay.FindAction("Movement", throwIfNotFound: true);
        m_Gameplay_UseTool = m_Gameplay.FindAction("UseTool", throwIfNotFound: true);
        m_Gameplay_PlantCrop1 = m_Gameplay.FindAction("PlantCrop1", throwIfNotFound: true);
        m_Gameplay_PlantCrop2 = m_Gameplay.FindAction("PlantCrop2", throwIfNotFound: true);
        m_Gameplay_PlantCrop3 = m_Gameplay.FindAction("PlantCrop3", throwIfNotFound: true);
        m_Gameplay_PlantCrop4 = m_Gameplay.FindAction("PlantCrop4", throwIfNotFound: true);
        m_Gameplay_PlantCrop5 = m_Gameplay.FindAction("PlantCrop5", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private IGameplayActions m_GameplayActionsCallbackInterface;
    private readonly InputAction m_Gameplay_PauseMenu;
    private readonly InputAction m_Gameplay_Movement;
    private readonly InputAction m_Gameplay_UseTool;
    private readonly InputAction m_Gameplay_PlantCrop1;
    private readonly InputAction m_Gameplay_PlantCrop2;
    private readonly InputAction m_Gameplay_PlantCrop3;
    private readonly InputAction m_Gameplay_PlantCrop4;
    private readonly InputAction m_Gameplay_PlantCrop5;
    public struct GameplayActions
    {
        private @PlayerControls m_Wrapper;
        public GameplayActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @PauseMenu => m_Wrapper.m_Gameplay_PauseMenu;
        public InputAction @Movement => m_Wrapper.m_Gameplay_Movement;
        public InputAction @UseTool => m_Wrapper.m_Gameplay_UseTool;
        public InputAction @PlantCrop1 => m_Wrapper.m_Gameplay_PlantCrop1;
        public InputAction @PlantCrop2 => m_Wrapper.m_Gameplay_PlantCrop2;
        public InputAction @PlantCrop3 => m_Wrapper.m_Gameplay_PlantCrop3;
        public InputAction @PlantCrop4 => m_Wrapper.m_Gameplay_PlantCrop4;
        public InputAction @PlantCrop5 => m_Wrapper.m_Gameplay_PlantCrop5;
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        public void SetCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterface != null)
            {
                @PauseMenu.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPauseMenu;
                @PauseMenu.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPauseMenu;
                @PauseMenu.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPauseMenu;
                @Movement.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMovement;
                @UseTool.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnUseTool;
                @UseTool.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnUseTool;
                @UseTool.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnUseTool;
                @PlantCrop1.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPlantCrop1;
                @PlantCrop1.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPlantCrop1;
                @PlantCrop1.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPlantCrop1;
                @PlantCrop2.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPlantCrop2;
                @PlantCrop2.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPlantCrop2;
                @PlantCrop2.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPlantCrop2;
                @PlantCrop3.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPlantCrop3;
                @PlantCrop3.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPlantCrop3;
                @PlantCrop3.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPlantCrop3;
                @PlantCrop4.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPlantCrop4;
                @PlantCrop4.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPlantCrop4;
                @PlantCrop4.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPlantCrop4;
                @PlantCrop5.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPlantCrop5;
                @PlantCrop5.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPlantCrop5;
                @PlantCrop5.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPlantCrop5;
            }
            m_Wrapper.m_GameplayActionsCallbackInterface = instance;
            if (instance != null)
            {
                @PauseMenu.started += instance.OnPauseMenu;
                @PauseMenu.performed += instance.OnPauseMenu;
                @PauseMenu.canceled += instance.OnPauseMenu;
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @UseTool.started += instance.OnUseTool;
                @UseTool.performed += instance.OnUseTool;
                @UseTool.canceled += instance.OnUseTool;
                @PlantCrop1.started += instance.OnPlantCrop1;
                @PlantCrop1.performed += instance.OnPlantCrop1;
                @PlantCrop1.canceled += instance.OnPlantCrop1;
                @PlantCrop2.started += instance.OnPlantCrop2;
                @PlantCrop2.performed += instance.OnPlantCrop2;
                @PlantCrop2.canceled += instance.OnPlantCrop2;
                @PlantCrop3.started += instance.OnPlantCrop3;
                @PlantCrop3.performed += instance.OnPlantCrop3;
                @PlantCrop3.canceled += instance.OnPlantCrop3;
                @PlantCrop4.started += instance.OnPlantCrop4;
                @PlantCrop4.performed += instance.OnPlantCrop4;
                @PlantCrop4.canceled += instance.OnPlantCrop4;
                @PlantCrop5.started += instance.OnPlantCrop5;
                @PlantCrop5.performed += instance.OnPlantCrop5;
                @PlantCrop5.canceled += instance.OnPlantCrop5;
            }
        }
    }
    public GameplayActions @Gameplay => new GameplayActions(this);
    private int m_Player1SchemeIndex = -1;
    public InputControlScheme Player1Scheme
    {
        get
        {
            if (m_Player1SchemeIndex == -1) m_Player1SchemeIndex = asset.FindControlSchemeIndex("Player1");
            return asset.controlSchemes[m_Player1SchemeIndex];
        }
    }
    private int m_Player2SchemeIndex = -1;
    public InputControlScheme Player2Scheme
    {
        get
        {
            if (m_Player2SchemeIndex == -1) m_Player2SchemeIndex = asset.FindControlSchemeIndex("Player2");
            return asset.controlSchemes[m_Player2SchemeIndex];
        }
    }
    public interface IGameplayActions
    {
        void OnPauseMenu(InputAction.CallbackContext context);
        void OnMovement(InputAction.CallbackContext context);
        void OnUseTool(InputAction.CallbackContext context);
        void OnPlantCrop1(InputAction.CallbackContext context);
        void OnPlantCrop2(InputAction.CallbackContext context);
        void OnPlantCrop3(InputAction.CallbackContext context);
        void OnPlantCrop4(InputAction.CallbackContext context);
        void OnPlantCrop5(InputAction.CallbackContext context);
    }
}
